### ISSUE TITLE
Scary Errors on initial startup

### ISSUE THREAD

**Issue by dabeeeenster** [BulletTrainHQ/bullet-train-docker#13]
I think the task processor image freaks out for a while until the main flagsmith image has run all the DB migrations:

```
flagsmith_postgres                 | 2023-06-14 14:24:57.705 UTC [29] ERROR:  function get_tasks_to_process(integer) does not exist at character 15
flagsmith_postgres                 | 2023-06-14 14:24:57.705 UTC [29] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
flagsmith_postgres                 | 2023-06-14 14:24:57.705 UTC [29] STATEMENT:  SELECT * FROM get_tasks_to_process(10)
flagsmith_postgres                 | 2023-06-14 14:24:57.705 UTC [33] ERROR:  function get_tasks_to_process(integer) does not exist at character 15
flagsmith_postgres                 | 2023-06-14 14:24:57.705 UTC [33] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
flagsmith_postgres                 | 2023-06-14 14:24:57.705 UTC [33] STATEMENT:  SELECT * FROM get_tasks_to_process(10)
flagsmith_postgres                 | 2023-06-14 14:24:57.707 UTC [31] ERROR:  function get_tasks_to_process(integer) does not exist at character 15
flagsmith_postgres                 | 2023-06-14 14:24:57.707 UTC [31] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
flagsmith_postgres                 | 2023-06-14 14:24:57.707 UTC [31] STATEMENT:  SELECT * FROM get_tasks_to_process(10)
flagsmith_postgres                 | 2023-06-14 14:24:57.708 UTC [32] ERROR:  function get_tasks_to_process(integer) does not exist at character 15
flagsmith_postgres                 | 2023-06-14 14:24:57.708 UTC [32] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
flagsmith_postgres                 | 2023-06-14 14:24:57.708 UTC [32] STATEMENT:  SELECT * FROM get_tasks_to_process(10)
flagsmith_postgres                 | 2023-06-14 14:24:57.708 UTC [30] ERROR:  function get_tasks_to_process(integer) does not exist at character 15
flagsmith_postgres                 | 2023-06-14 14:24:57.708 UTC [30] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
flagsmith_postgres                 | 2023-06-14 14:24:57.708 UTC [30] STATEMENT:  SELECT * FROM get_tasks_to_process(10)
self-hosted-flagsmith_processor-1  | task_processor.threads ERROR    function get_tasks_to_process(integer) does not exist
self-hosted-flagsmith_processor-1  | LINE 1: SELECT * FROM get_tasks_to_process(10)
self-hosted-flagsmith_processor-1  |                       ^
self-hosted-flagsmith_processor-1  | HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
self-hosted-flagsmith_processor-1  | Traceback (most recent call last):
self-hosted-flagsmith_processor-1  |   File "/opt/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
self-hosted-flagsmith_processor-1  |     return self.cursor.execute(sql, params)
self-hosted-flagsmith_processor-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
self-hosted-flagsmith_processor-1  | psycopg2.errors.UndefinedFunction: function get_tasks_to_process(integer) does not exist
self-hosted-flagsmith_processor-1  | LINE 1: SELECT * FROM get_tasks_to_process(10)
self-hosted-flagsmith_processor-1  |                       ^
self-hosted-flagsmith_processor-1  | HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
self-hosted-flagsmith_processor-1  |
self-hosted-flagsmith_processor-1  |
self-hosted-flagsmith_processor-1  | The above exception was the direct cause of the following exception:
self-hosted-flagsmith_processor-1  |
self-hosted-flagsmith_processor-1  | Traceback (most recent call last):
self-hosted-flagsmith_processor-1  |   File "/app/task_processor/threads.py", line 31, in run
self-hosted-flagsmith_processor-1  |     run_tasks(self.queue_pop_size)
self-hosted-flagsmith_processor-1  |   File "/app/task_processor/processor.py", line 24, in run_tasks
self-hosted-flagsmith_processor-1  |     if tasks:
self-hosted-flagsmith_processor-1  |   File "/opt/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1480, in __bool__
self-hosted-flagsmith_processor-1  |     self._fetch_all()
self-hosted-flagsmith_processor-1  |   File "/opt/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1471, in _fetch_all
self-hosted-flagsmith_processor-1  |     self._result_cache = list(self.iterator())
self-hosted-flagsmith_processor-1  |                          ^^^^^^^^^^^^^^^^^^^^^
self-hosted-flagsmith_processor-1  |   File "/opt/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1494, in iterator
self-hosted-flagsmith_processor-1  |     query = iter(self.query)
self-hosted-flagsmith_processor-1  |             ^^^^^^^^^^^^^^^^
self-hosted-flagsmith_processor-1  |   File "/opt/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 110, in __iter__
self-hosted-flagsmith_processor-1  |     self._execute_query()
self-hosted-flagsmith_processor-1  |   File "/opt/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 150, in _execute_query
self-hosted-flagsmith_processor-1  |     self.cursor.execute(self.sql, params)
self-hosted-flagsmith_processor-1  |   File "/opt/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 66, in execute
self-hosted-flagsmith_processor-1  |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
self-hosted-flagsmith_processor-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
self-hosted-flagsmith_processor-1  |   File "/opt/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
self-hosted-flagsmith_processor-1  |     return executor(sql, params, many, context)
self-hosted-flagsmith_processor-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
self-hosted-flagsmith_processor-1  |   File "/opt/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in _execute
self-hosted-flagsmith_processor-1  |     with self.db.wrap_database_errors:
self-hosted-flagsmith_processor-1  |   File "/opt/venv/lib/python3.11/site-packages/django/db/utils.py", line 90, in __exit__
self-hosted-flagsmith_processor-1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
self-hosted-flagsmith_processor-1  |   File "/opt/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
self-hosted-flagsmith_processor-1  |     return self.cursor.execute(sql, params)
self-hosted-flagsmith_processor-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
self-hosted-flagsmith_processor-1  | django.db.utils.ProgrammingError: function get_tasks_to_process(integer) does not exist
self-hosted-flagsmith_processor-1  | LINE 1: SELECT * FROM get_tasks_to_process(10)
self-hosted-flagsmith_processor-1  |                       ^
self-hosted-flagsmith_processor-1  | HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
self-hosted-flagsmith_processor-1  |
flagsmith_postgres                 | 2023-06-14 14:24:57.710 UTC [29] ERROR:  function get_recurringtasks_to_process(integer) does not exist at character 15
flagsmith_postgres                 | 2023-06-14 14:24:57.710 UTC [29] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
flagsmith_postgres                 | 2023-06-14 14:24:57.710 UTC [29] STATEMENT:  SELECT * FROM get_recurringtasks_to_process(10)
self-hosted-flagsmith_processor-1  | Exception in thread Thread-1:
```

I then get warnings being spammed to the console:

```
self-hosted-flagsmith_processor-1  | task_processor.thread_monitoring WARNING  Writing unhealthy threads: ['Thread-1', 'Thread-2', 'Thread-3', 'Thread-4', 'Thread-5']
self-hosted-flagsmith_processor-1  | task_processor.thread_monitoring WARNING  Writing unhealthy threads: ['Thread-1', 'Thread-2', 'Thread-3', 'Thread-4', 'Thread-5']
self-hosted-flagsmith_processor-1  | task_processor.thread_monitoring WARNING  Writing unhealthy threads: ['Thread-1', 'Thread-2', 'Thread-3', 'Thread-4', 'Thread-5']
self-hosted-flagsmith_processor-1  | task_processor.thread_monitoring WARNING  Writing unhealthy threads: ['Thread-1', 'Thread-2', 'Thread-3', 'Thread-4', 'Thread-5']
self-hosted-flagsmith_processor-1  | task_processor.thread_monitoring WARNING  Writing unhealthy threads: ['Thread-1', 'Thread-2', 'Thread-3', 'Thread-4', 'Thread-5']
self-hosted-flagsmith_processor-1  | task_processor.thread_monitoring WARNING  Writing unhealthy threads: ['Thread-1', 'Thread-2', 'Thread-3', 'Thread-4', 'Thread-5']
self-hosted-flagsmith_processor-1  | task_processor.thread_monitoring WARNING  Writing unhealthy threads: ['Thread-1', 'Thread-2', 'Thread-3', 'Thread-4', 'Thread-5']
self-hosted-flagsmith_processor-1  | task_processor.thread_monitoring WARNING  Writing unhealthy threads: ['Thread-1', 'Thread-2', 'Thread-3', 'Thread-4', 'Thread-5']
self-hosted-flagsmith_processor-1  | task_processor.thread_monitoring WARNING  Writing unhealthy threads: ['Thread-1', 'Thread-2', 'Thread-3', 'Thread-4', 'Thread-5']
self-hosted-flagsmith_processor-1  | task_processor.thread_monitoring WARNING  Writing unhealthy threads: ['Thread-1', 'Thread-2', 'Thread-3', 'Thread-4', 'Thread-5']
self-hosted-flagsmith_processor-1  | task_processor.thread_monitoring WARNING  Writing unhealthy threads: ['Thread-1', 'Thread-2', 'Thread-3', 'Thread-4', 'Thread-5']
self-hosted-flagsmith_processor-1  | task_processor.thread_monitoring WARNING  Writing unhealthy threads: ['Thread-1', 'Thread-2', 'Thread-3', 'Thread-4', 'Thread-5']
self-hosted-flagsmith_processor-1  | task_processor.thread_monitoring WARNING  Writing unhealthy threads: ['Thread-1', 'Thread-2', 'Thread-3', 'Thread-4', 'Thread-5']
self-hosted-flagsmith_processor-1  | task_processor.thread_monitoring WARNING  Writing unhealthy threads: ['Thread-1', 'Thread-2', 'Thread-3', 'Thread-4', 'Thread-5']
self-hosted-flagsmith_processor-1  | task_processor.thread_monitoring WARNING  Writing unhealthy threads: ['Thread-1', 'Thread-2', 'Thread-3', 'Thread-4', 'Thread-5']
self-hosted-flagsmith_processor-1  | task_processor.thread_monitoring WARNING  Writing unhealthy threads: ['Thread-1', 'Thread-2', 'Thread-3', 'Thread-4', 'Thread-5']
self-hosted-flagsmith_processor-1  | task_processor.thread_monitoring WARNING  Writing unhealthy threads: ['Thread-1', 'Thread-2', 'Thread-3', 'Thread-4', 'Thread-5']
self-hosted-flagsmith_processor-1  | task_processor.thread_monitoring WARNING  Writing unhealthy threads: ['Thread-1', 'Thread-2', 'Thread-3', 'Thread-4', 'Thread-5']
self-hosted-flagsmith_processor-1  | task_processor.thread_monitoring WARNING  Writing unhealthy threads: ['Thread-1', 'Thread-2', 'Thread-3', 'Thread-4', 'Thread-5']
self-hosted-flagsmith_processor-1  | task_processor.thread_monitoring WARNING  Writing unhealthy threads: ['Thread-1', 'Thread-2', 'Thread-3', 'Thread-4', 'Thread-5']
self-hosted-flagsmith_processor-1  | task_processor.thread_monitoring WARNING  Writing unhealthy threads: ['Thread-1', 'Thread-2', 'Thread-3', 'Thread-4', 'Thread-5']
self-hosted-flagsmith_processor-1  | task_processor.thread_monitoring WARNING  Writing unhealthy threads: ['Thread-1', 'Thread-2', 'Thread-3', 'Thread-4', 'Thread-5']
self-hosted-flagsmith_processor-1  | task_processor.thread_monitoring WARNING  Writing unhealthy threads: ['Thread-1', 'Thread-2', 'Thread-3', 'Thread-4', 'Thread-5']
```

running `docker-compose down; docker-compose up` then brings everythign up cleanly

**Comment by khvn26** [comment]
Yep the entrypoint should be changed. Easy fix and I have it locally but I still don't have permissions to push to this repo.

**Comment by dabeeeenster** [comment]
> Yep the entrypoint should be changed. Easy fix and I have it locally but I still don't have permissions to push to this repo.

Should have permission now!
